---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springhelloworlddepl
  namespace: meenakshisundaram-1447031
spec:
  selector:
    matchLabels:
      app: springhelloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: springhelloworld
    spec:
      containers:
      - name: springhelloworldcontainer
        image: sundar2710/springboothello:latest
        resources:
          limits:
            memory: 2Gi
            cpu: "1"
          requests:
            memory: 500Mi
            cpu: 250m

---

apiVersion: v1
kind: Service
metadata:
  name: springhelloworldsvc
  namespace: meenakshisundaram-1447031
spec:
  ports:
    - name: springhellowroldport
      port: 9000
  type: ClusterIP
  selector:
    app: springhelloworld

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sundaringress
  namespace: meenakshisundaram-1447031
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /sundar(/|$)(.*)
            backend:
              serviceName: springhelloworldsvc
              servicePort: 9000
